p8105_hw2_ms7354
================
Maliha Safdar
2025-09-30

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.4     ✔ readr     2.1.5
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.1
    ## ✔ ggplot2   4.0.0     ✔ tibble    3.3.0
    ## ✔ lubridate 1.9.4     ✔ tidyr     1.3.1
    ## ✔ purrr     1.1.0     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library(dplyr)
library(readr)
library(readxl)
```

### Problem 1

``` r
pols_month_df = 
  read.csv("./data/pols-month.csv") |>
  janitor::clean_names()

mon_separated <- pols_month_df |>
  separate(mon,into = c("year", "month", "date"), sep = "-") |>
  mutate(
    year  = as.integer(year),
    month = as.integer(month),
    date  = as.integer(date),
    month = month.name[month],
    president = 
      case_match(
        prez_gop, 
        0 ~ "dem", 
        1 ~ "gop"),
    prez_gop = as.factor(prez_gop)
    ) |>
  select(-prez_dem, -prez_gop, -date) |>
  relocate(year,month, president)
```

``` r
snp_df = 
  read.csv("./data/snp.csv") |>
  janitor::clean_names()

snp_date_separated <- snp_df |>
  separate(date, into = c ("day", "month", "year"), sep = "/") |>
  mutate(
    day = as.integer(day),
    month = as.integer(month),
    year = as.integer(year),
    month = month.name[month],
     year = case_when(
      year <= 24         ~ 2000L + year,
      TRUE               ~ 1900L + year
      
  )
    )|>
  select(-day) |>
  relocate(year, month)
```

``` r
unemployment_df =
  read.csv("./data/unemployment.csv") |>
  janitor::clean_names()

unemployment_tidy_df = 
  pivot_longer(
    unemployment_df, 
    jan:dec,
    names_to = "month", 
    values_to = "percentage_unemployed") |>
  mutate(
    month = factor(
      str_to_title(month),
      levels = month.abb,
      labels = base::month.name,
      ordered = TRUE
    )
  ) |>
  relocate(year,month)
```

`Joining the three datasets.`

``` r
snp_pols =
  left_join(mon_separated,snp_date_separated, by = c("year", "month"))

final_df =
  left_join(unemployment_tidy_df,snp_pols, by = c("year", "month")) |>
  relocate("year", "month", "president", "percentage_unemployed", "close")

head(final_df)
```

    ## # A tibble: 6 × 11
    ##    year month    president percentage_unemployed close gov_gop sen_gop rep_gop
    ##   <int> <chr>    <chr>                     <dbl> <dbl>   <int>   <int>   <int>
    ## 1  1948 January  dem                         3.4    NA      22      53     253
    ## 2  1948 February dem                         3.8    NA      22      53     253
    ## 3  1948 March    dem                         4      NA      22      53     253
    ## 4  1948 April    dem                         3.9    NA      22      53     253
    ## 5  1948 May      dem                         3.5    NA      22      53     253
    ## 6  1948 June     dem                         3.6    NA      22      53     253
    ## # ℹ 3 more variables: gov_dem <int>, sen_dem <int>, rep_dem <int>

``` r
tail(final_df)
```

    ## # A tibble: 6 × 11
    ##    year month     president percentage_unemployed close gov_gop sen_gop rep_gop
    ##   <int> <chr>     <chr>                     <dbl> <dbl>   <int>   <int>   <int>
    ## 1  2015 July      <NA>                         NA    NA      NA      NA      NA
    ## 2  2015 August    <NA>                         NA    NA      NA      NA      NA
    ## 3  2015 September <NA>                         NA    NA      NA      NA      NA
    ## 4  2015 October   <NA>                         NA    NA      NA      NA      NA
    ## 5  2015 November  <NA>                         NA    NA      NA      NA      NA
    ## 6  2015 December  <NA>                         NA    NA      NA      NA      NA
    ## # ℹ 3 more variables: gov_dem <int>, sen_dem <int>, rep_dem <int>

`The pol_mon dataset contains data related to national politicians who are democratic or republican at any given time. The snp dataset contains data related to Standard & Poor's stock market index (S&P) which is usually used as a representative measure of stock market as a whole. The umemployment dataset contains information about percentage of unemployment by year and month. The final dataset that contains the above mentioned three datasets gives us information on when democratic or republican politicians are elected and the s&p stock market price and unemployment percentages over the period of years. The final dataset has 1385 observations, and ranges from 1948 to 2015, so a range of 67 years, and the key varaiables are year, month, percent_unemployed, president and close.`

### Problem 2

``` r
mr_trash <- readxl::read_excel("./data/202509 Trash Wheel Collection Data.xlsx",
  sheet = "Mr. Trash Wheel",
  range = "A2:N709") |>
  janitor::clean_names() |>
  mutate(
  sports_balls = as.integer(round(sports_balls)),
  homes_powered = as.integer(round(homes_powered)),
  year = as.numeric(year),
  trash_name = "mr_trash"
  )|>
  select( -"date") |>
  relocate(year, month)
```

``` r
prof_trash <- readxl::read_excel("./data/202509 Trash Wheel Collection Data.xlsx",
  sheet = "Professor Trash Wheel",
  range = "A2:M134") |>
  janitor::clean_names() |>
  select( -"date") |>
  relocate(year, month, dumpster) |>
  mutate(
  homes_powered = as.integer(round(homes_powered)),
  trash_name = "prof_trash",
  year = as.numeric(year)
  )
```

``` r
gwynnda <- readxl::read_excel("./data/202509 Trash Wheel Collection Data.xlsx",
  sheet = "Gwynns Falls Trash Wheel",
  range = "A2:L351") |>
  janitor::clean_names() |>
  select( -"date") |>
  relocate(year, month, dumpster) |>
  mutate(
  homes_powered = as.integer(round(homes_powered)),
  trash_name = "gwynnda"
  )
```

`Combining all three datasets.`

``` r
trash_all =
  bind_rows(mr_trash,prof_trash,gwynnda) |>
  janitor::clean_names() |>
  select(trash_name, everything()) |>
  relocate(trash_name, year, month, dumpster)

prof_weight_tons <- sum(prof_trash$weight_tons, na.rm = TRUE)


trash_tidy_all = 
  pivot_longer(
    trash_all,
    plastic_bottles:sports_balls,
    names_to = "trash_type",
    values_to = "units_collected"
  ) |>
  relocate(trash_name, year, month, dumpster, trash_type, units_collected)
```

``` r
cigarrette_buds_gwynnda =
  bind_rows(mr_trash,prof_trash,gwynnda) |>
  janitor::clean_names() |>
  select(trash_name, everything()) |>
  relocate(trash_name, year, month, dumpster) |>
  filter(trash_name == "gwynnda", year == 2022, month %in% c("June","Jun")) |>
  summarise(total_cig_butts = sum(cigarette_butts, na.rm = TRUE))
```

`The resulting dataset is trash_all which contains the trash in weight (tons) and volume(cubic yards) along with the different types of trash collected accross a period of time. It contains the trash that has been collected from Mr. Trash Wheel, Professor Trash Wheel and Gwynns Fall Trash Wheel which are the names given to the different trash wheel at different locations. The trash_all dataset has 1188 observations with data collected from 2014 up until 2025. The key variables are year, month, trash_name, weight_tons, and volume_cubic_yd. The total weight in tons of trash collected by Professor Trash Wheel is 282.26 in tons. The total number of cigarrette butts collected by gwynnda in 2022 was 18120.`

### Problem 3

``` r
zori =
  read.csv("./data/Zip_zori_uc_sfrcondomfr_sm_month_NYC.csv") |>
  janitor::clean_names() |>
  rename(zip_code = region_name) |>
  pivot_longer(
    -(region_id:county_name),
    names_to = "date",
    values_to = "rent_price"
  ) |>
  mutate(
  date = str_remove(date,"x"),
    date = ymd(date)
  )


zip_codes = 
  read.csv("./data/Zip Codes.csv") |>
  janitor::clean_names() |>
  mutate(
    county_name = 
        case_match(
        county,
        "Bronx" ~ "Bronx County",
        "Kings" ~ "Kings County",
        "New York" ~ "New York County",
        "Queens" ~ "Queens County",
        "Richmond" ~ "Richmond County")
    
  )|>
  relocate(zip_code,neighborhood, county_name,county_code)
```

`Joining both the datasets. Before joining I want to look which observations might be missing or NA.`

``` r
missing_values = 
  anti_join(zori,zip_codes)
```

    ## Joining with `by = join_by(zip_code, county_name)`

``` r
#Queens county zip code 11693 has 116 obs that have NA rent price.

zori_zip =
  left_join(zori,zip_codes, by = c("zip_code", "county_name")) |>
  relocate(date,county_name, neighborhood,rent_price,zip_code) |>
  mutate(
    zip_code = as.character(zip_code)
  )
skimr::skim(zori_zip)
```

|                                                  |          |
|:-------------------------------------------------|:---------|
| Name                                             | zori_zip |
| Number of rows                                   | 17284    |
| Number of columns                                | 17       |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_   |          |
| Column type frequency:                           |          |
| character                                        | 10       |
| Date                                             | 1        |
| numeric                                          | 6        |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ |          |
| Group variables                                  | None     |

Data summary

**Variable type: character**

| skim_variable | n_missing | complete_rate | min | max | empty | n_unique | whitespace |
|:--------------|----------:|--------------:|----:|----:|------:|---------:|-----------:|
| county_name   |         0 |          1.00 |  12 |  15 |     0 |        5 |          0 |
| neighborhood  |       696 |          0.96 |   7 |  29 |     0 |       42 |          0 |
| zip_code      |         0 |          1.00 |   5 |   5 |     0 |      149 |          0 |
| region_type   |         0 |          1.00 |   3 |   3 |     0 |        1 |          0 |
| state_name    |         0 |          1.00 |   2 |   2 |     0 |        1 |          0 |
| state         |         0 |          1.00 |   2 |   2 |     0 |        1 |          0 |
| city          |         0 |          1.00 |   8 |   8 |     0 |        1 |          0 |
| metro         |         0 |          1.00 |  37 |  37 |     0 |        1 |          0 |
| county        |       116 |          0.99 |   5 |   8 |     0 |        5 |          0 |
| file_date     |       116 |          0.99 |   7 |   7 |     0 |        1 |          0 |

**Variable type: Date**

| skim_variable | n_missing | complete_rate | min | max | median | n_unique |
|:---|---:|---:|:---|:---|:---|---:|
| date | 0 | 1 | 2015-01-31 | 2024-08-31 | 2019-11-15 | 116 |

**Variable type: numeric**

| skim_variable | n_missing | complete_rate | mean | sd | p0 | p25 | p50 | p75 | p100 | hist |
|:---|---:|---:|---:|---:|---:|---:|---:|---:|---:|:---|
| rent_price | 6834 | 0.60 | 2889.11 | 884.05 | 1102.4 | 2244.18 | 2701.29 | 3373.24 | 8422.62 | ▇▇▂▁▁ |
| region_id | 0 | 1.00 | 66415.47 | 38858.63 | 61615.0 | 61657.00 | 62005.00 | 62045.00 | 399546.00 | ▇▁▁▁▁ |
| size_rank | 0 | 1.00 | 2533.31 | 4014.37 | 4.0 | 142.00 | 1025.00 | 3485.00 | 30490.00 | ▇▁▁▁▁ |
| county_code | 116 | 0.99 | 55.57 | 24.81 | 5.0 | 47.00 | 61.00 | 81.00 | 85.00 | ▃▁▆▇▇ |
| state_fips | 116 | 0.99 | 36.00 | 0.00 | 36.0 | 36.00 | 36.00 | 36.00 | 36.00 | ▁▁▇▁▁ |
| county_fips | 116 | 0.99 | 36055.57 | 24.81 | 36005.0 | 36047.00 | 36061.00 | 36081.00 | 36085.00 | ▃▁▆▇▇ |

`There are a total of 17284 observations in this resulting tidy dataset which I have indicated as zori_zip. There are 149 unique zip codes and 42 unique neighborhoods.`

``` r
zori_zip =
  left_join(zori,zip_codes, by = c("zip_code", "county_name")) |>
  relocate(date,county_name, neighborhood,rent_price,zip_code)

zori_zip_missing =
  anti_join(zip_codes,zori, by = "zip_code") |>
  mutate(
    zip_code = as.character(zip_code)
  )

  skimr::skim(zori_zip_missing)
```

|                                                  |                  |
|:-------------------------------------------------|:-----------------|
| Name                                             | zori_zip_missing |
| Number of rows                                   | 171              |
| Number of columns                                | 8                |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_   |                  |
| Column type frequency:                           |                  |
| character                                        | 5                |
| numeric                                          | 3                |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ |                  |
| Group variables                                  | None             |

Data summary

**Variable type: character**

| skim_variable | n_missing | complete_rate | min | max | empty | n_unique | whitespace |
|:--------------|----------:|--------------:|----:|----:|------:|---------:|-----------:|
| zip_code      |         0 |           1.0 |   5 |   5 |     0 |      171 |          0 |
| neighborhood  |       137 |           0.2 |   7 |  26 |     0 |       14 |          0 |
| county_name   |         0 |           1.0 |  12 |  15 |     0 |        5 |          0 |
| county        |         0 |           1.0 |   5 |   8 |     0 |        5 |          0 |
| file_date     |         0 |           1.0 |   7 |   7 |     0 |        1 |          0 |

**Variable type: numeric**

| skim_variable | n_missing | complete_rate | mean | sd | p0 | p25 | p50 | p75 | p100 | hist |
|:---|---:|---:|---:|---:|---:|---:|---:|---:|---:|:---|
| county_code | 0 | 1 | 63.47 | 16.67 | 5 | 61 | 61 | 81 | 85 | ▁▁▁▇▃ |
| state_fips | 0 | 1 | 36.00 | 0.00 | 36 | 36 | 36 | 36 | 36 | ▁▁▇▁▁ |
| county_fips | 0 | 1 | 36063.47 | 16.67 | 36005 | 36061 | 36061 | 36081 | 36085 | ▁▁▁▇▃ |

`There are 171 zip codes that appear in zip_codes dataset but not in the zori dataset. Some examples of missing zip codes from the zori dataset are as follows:`

``` r
head(zori_zip_missing, 6) |>
knitr::kable()
```

| zip_code | neighborhood | county_name | county_code | county | state_fips | county_fips | file_date |
|:---|:---|:---|---:|:---|---:|---:|:---|
| 10464 | Southeast Bronx | Bronx County | 5 | Bronx | 36 | 36005 | 7/25/07 |
| 10474 | Hunts Point and Mott Haven | Bronx County | 5 | Bronx | 36 | 36005 | 7/25/07 |
| 10475 | Northeast Bronx | Bronx County | 5 | Bronx | 36 | 36005 | 7/25/07 |
| 10499 | NA | Bronx County | 5 | Bronx | 36 | 36005 | 7/25/07 |
| 10550 | NA | Bronx County | 5 | Bronx | 36 | 36005 | 7/25/07 |
| 10704 | NA | Bronx County | 5 | Bronx | 36 | 36005 | 7/25/07 |

``` r
price_change = zori_zip |>
  filter(
    date %in% c ("2020-01-31","2021-01-31")) |>
  select(zip_code,county_name,neighborhood,date, rent_price) |>
  pivot_wider(
    names_from = date,
    values_from = rent_price) |> # separated the date columns by rent price so now they show the difference or change in rent price. 
  mutate(
    county_name = 
        case_match(
        county_name,
        "Bronx County" ~ "The Bronx",
        "Kings County" ~ "Brooklyn",
        "New York County" ~ "Manhattan",
        "Queens County" ~ "Queens",
        "Richmond County" ~ "Staten Island"),
    price_fluc = `2021-01-31` - `2020-01-31`) |>
    drop_na(neighborhood) |>
    rename(bourough = "county_name") |>
    arrange(price_fluc)
  
head(price_change, 10) |>
knitr::kable()
```

| zip_code | bourough | neighborhood | 2020-01-31 | 2021-01-31 | price_fluc |
|---:|:---|:---|---:|---:|---:|
| 10007 | Manhattan | Lower Manhattan | 6334.211 | 5421.614 | -912.5966 |
| 10009 | Manhattan | Lower East Side | 3406.442 | 2692.187 | -714.2550 |
| 10016 | Manhattan | Gramercy Park and Murray Hill | 3731.135 | 3019.431 | -711.7045 |
| 10001 | Manhattan | Chelsea and Clinton | 4108.098 | 3397.648 | -710.4499 |
| 10002 | Manhattan | Lower East Side | 3645.416 | 2935.113 | -710.3028 |
| 10004 | Manhattan | Lower Manhattan | 3149.658 | 2443.697 | -705.9608 |
| 10038 | Manhattan | Lower Manhattan | 3573.201 | 2875.616 | -697.5853 |
| 10012 | Manhattan | Greenwich Village and Soho | 3628.566 | 2942.344 | -686.2218 |
| 10010 | Manhattan | Gramercy Park and Murray Hill | 3697.284 | 3012.353 | -684.9304 |
| 10003 | Manhattan | Lower East Side | 3569.784 | 2897.243 | -672.5404 |

`In the table above, we can see that the largest drop in rent price was $913 in the Manhattan bourough, in lower Manhattan neighborhood. On January 31st of 2020 the rent price was $6334 and exactly one year later it dropped to $5422.`
